title: Longlong Li's Homepage
page-top-title: Longlong Li
home-subtitle: 'Longlong Li &ensp;|&ensp; 李龙龙<a href="https://orcid.org/0009-0001-0079-3093" target="_blank" style="text-decoration:none;"><img src="https://orcid.org/assets/vectors/orcid.logo.icon.svg" alt="ORCID" style="width:30px; height:30px; position:relative; top:-0.6em; margin-left:4px; vertical-align:middle;"></a>'
copyright-text: '&copy; Longlong Li 2025. All Rights Reserved.'
