title: Longlong Li's Homepage
page-top-title: Longlong Li
home-subtitle: 'Longlong Li &ensp;|&ensp; 李龙龙 &ensp;|&ensp; <a href="https://orcid.org/0009-0001-0079-3093" target="_blank">ORCID</a>'
copyright-text: '&copy; Longlong Li 2025. All Rights Reserved.'
